version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: tests
          command: |
            . venv/bin/activate
            pytest -vvv tests

      - run:
         name: lint
         command: |
           . venv/bin/activate
           pylint configular

      - store_artifacts:
          path: test-reports
          destination: test-reports
